### PR TITLE
Update offsets for version 1.04 (03/06/2016)

### LINKED ISSUE #10: Breaks with latest patch from TODAY
Doesn't work with latest patch, big surprise. Thanks, Square.

### PR DESCRIPTION
**Pull request by xforce**
I uploaded a new compiled version to my forks releases, found here https://github.com/xforce/justfov/releases/tag/1.3
This fixes #10

### CODE REVIEW

**Comment by mumair85** [comment]
Its probably best to leave the version numbers to owner and ignore the files .sln and .csproj as the only useful change is in JustFOV/Model.cs, what do you think?

**Comment by xforce** [comment]
Oh ups, didn't mean to commit the project files. I will revert them and update this PR

**Comment by trixnz** [comment]
Thanks! I've been super busy and haven't been able to update this. Looks great

**Comment by methodbox** [comment]
@xforce Any chance you can take a look @ this regarding the 1.05 patch that dropped today?

I don't even know where to start - assembly is outside my scope.

**Pull request merged**
